// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsStats.API.Data;

#nullable disable

namespace SportsStats.API.Migrations
{
    [DbContext(typeof(SportsStatsDbContext))]
    partial class SportsStatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsStats.API.Models.Entities.CachedPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalPlayerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId", "ExternalPlayerId")
                        .IsUnique();

                    b.ToTable("CachedPlayers");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.CachedStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CachedPlayerId")
                        .HasColumnType("int");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Season")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CachedPlayerId");

                    b.ToTable("CachedStats");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.SeasonStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("datetime2");

                    b.Property<int>("SportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SportId")
                        .IsUnique();

                    b.ToTable("SeasonStatuses");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiSportsBaseUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ApiSportsLeagueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiSportsBaseUrl = "https://v1.american-football.api-sports.io",
                            ApiSportsLeagueId = "1",
                            Name = "NFL",
                            Slug = "nfl"
                        },
                        new
                        {
                            Id = 2,
                            ApiSportsBaseUrl = "https://v1.basketball.api-sports.io",
                            ApiSportsLeagueId = "12",
                            Name = "NBA",
                            Slug = "nba"
                        },
                        new
                        {
                            Id = 3,
                            ApiSportsBaseUrl = "https://v1.baseball.api-sports.io",
                            ApiSportsLeagueId = "1",
                            Name = "MLB",
                            Slug = "mlb"
                        },
                        new
                        {
                            Id = 4,
                            ApiSportsBaseUrl = "https://v1.hockey.api-sports.io",
                            ApiSportsLeagueId = "57",
                            Name = "NHL",
                            Slug = "nhl"
                        },
                        new
                        {
                            Id = 5,
                            ApiSportsBaseUrl = "https://v3.football.api-sports.io",
                            ApiSportsLeagueId = "253",
                            Name = "MLS",
                            Slug = "mls"
                        });
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.CachedPlayer", b =>
                {
                    b.HasOne("SportsStats.API.Models.Entities.Sport", "Sport")
                        .WithMany("CachedPlayers")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.CachedStat", b =>
                {
                    b.HasOne("SportsStats.API.Models.Entities.CachedPlayer", "Player")
                        .WithMany("CachedStats")
                        .HasForeignKey("CachedPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.SeasonStatus", b =>
                {
                    b.HasOne("SportsStats.API.Models.Entities.Sport", "Sport")
                        .WithOne("SeasonStatus")
                        .HasForeignKey("SportsStats.API.Models.Entities.SeasonStatus", "SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.CachedPlayer", b =>
                {
                    b.Navigation("CachedStats");
                });

            modelBuilder.Entity("SportsStats.API.Models.Entities.Sport", b =>
                {
                    b.Navigation("CachedPlayers");

                    b.Navigation("SeasonStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
